### ISSUE TITLE
[1.18.2] failed to load a valid ResourcePackInfo

### ISSUE THREAD

**Issue by cleakey** [Reforged-Mods/Traverse-Reforged#3]
After installing this mod and the mods required by this mod, the following warning message appears after the MOJANG STUDIOS scene after the game starts

Waring while loading mods
1 warning has occurred during loading 

File Mod File: failed to load a valid ResourcePackInfo

File Mod File: C\Users\ ...\traverse-5.1.4.jar failed to load a valid ResourcePackInfo

The versions of the game and mods are as follows
minecraft 1.18.2
1.18.2-forge-40.2.9
traverse-5.1.4
terraform-forge-3.1.4
TerraBlender-forge-1.18.2-1.2.0.126

**Comment by Lozf** [comment]
I have the same issue.  Also, when trying to play both Traverse and Terrestria at the same time it crashes with an exit code of 1, and the log barely loads anything; https://gist.github.com/Lozf/6d2f634a73284df258767645a3bacfad.  This is also with the Fabric Biome API Reforged installed.

**Comment by Trinsdar** [comment]
Will look into it

**Comment by Trinsdar** [comment]
ok fixed the resource pack info issue, ~~the latter issue might be more difficult though, as I suspect why it happens, but if I'm right it means jar in jar is actually still broken in 1.18 and I'm kinda fucked, because forge is fucking dumb~~ nvm turns out forge fixed in in 40.2.3 finally

**Comment by Trinsdar** [comment]
can confirm with latest commit seems to be fixed. new uploads coming soon

**Comment by Lozf** [comment]
Just tested it out, they both work together and Traverse loaded everything with no problem.  Thanks for fixing it so fast!  Love playing those two together.
