### ISSUE TITLE
Server failed to load mod Invalid for Dedicated Server 1.19.2

### ISSUE THREAD

**Issue by ArcaneSan** [Reforged-Mods/Traverse-Reforged#6]
When attempting to load traverse reforged on a server an error for -- MOD traverse_client -- fails to load. 

It's pointing at mods/traverse-forge-6.2.4.jar#546!/META-INF/jars/traverse-client-6.2.4.jar and

For some reason it's showing traverse as a client mod and not for a server

[crash-2023-08-11_19.39.52-fml.txt](https://github.com/Reforged-Mods/Traverse-Reforged/files/12326319/crash-2023-08-11_19.39.52-fml.txt)

**Comment by Darkmega18** [comment]
I am also having this issue also. something about a client sided traverse and guis.

**Comment by Runburner** [comment]
I am getting this exact issue in1.18.2 on Traverse Reforged 5.1.5

**Comment by Recentiv** [comment]
bump

**Comment by Speiger** [comment]
how to fix traverse for 1.19.2

- 1: Open the jar.
- 2: Go into the "META-INF/jars" folder.
- 3: Delete traverese-client
- 4: Go into the "META-INF/jarjar" folder
- 5: Open the metadata json.
- 6: Delete the entry where the "identifier" says "client"
- 7: Save the json file.
- 8: Start on the server.

That should fix it easily.

**Comment by Trinsdar** [comment]
fixed
